from rules.dafiti import validate_dafiti_dom
from rules.kanui import validate_kanui_dom
from rules.shop2gether import validate_shop2gether_dom
from rules.artwalk import validate_artwalk_adidas_dom
from rules.gdlp import validate_gdlp_dom
from rules.maze import validate_maze_dom
from rules.yourid import validate_yourid_dom
from rules.kings import validate_kings_dom
from rules.authenticfeet import validate_authenticfeet_adidas_dom
from rules.farfetch import validate_farfetch_dom
from rules.pineapple import validate_pineapple_dom